# ruff: noqa: B018, F821
"""Reviewed dynamic/public surfaces for Vulture's 60% confidence gate.

This file is intentionally data, not executable code.  Every name below is
consumed through serialization, a framework registry/decorator, a protocol, or
the supported public API.  Keep this list explicit so a new 60% finding fails
CI until it is removed, given a real caller, or reviewed here.
"""

# Serialized dataclass/Pydantic contract fields.
qualification_requirements
prepared_at
admitted_at
observed_predictions
measured_cost_cells
unmeasured_cost_cells
input_lock_sha256
finalized_at
active_runs
remaining_cost_usd
status_digest
# Durable execution-recovery snapshot fields are serialized for operator
# inspection and controller rehydration rather than read by package code.
inspected_harbor_resources
discovered_harbor_resources
removed_harbor_resources
remaining_harbor_resources
cleanup_receipt_reference
cost_source
cost_receipt_reference
canonical_reconciliation
event_count
event_chain_digest
private_labels_digest
declared_changes
deterministic_evaluators
judge_evaluators
readiness_digest
deterministic_summary
signer
signed_at
queried_projects
weave_agent_root_call_id
otel_root_span_id
pair_id
baseline_prediction_id
candidate_prediction_id
baseline_evaluation_call_id
candidate_evaluation_call_id
improved_pairs
regressed_pairs
mixed_pairs
unchanged_pairs
incomplete_pairs
candidate_source_revisions
discriminating_dimensions
baseline_explanation
candidate_explanation
sanitized_answer_excerpt
reported_project_identity
tool_manifest_digest
license_url
discovery_skill_repositories
discovery_integration_registries
candidate_marker
official_popularity_exception
workspace_digest
patch_sha256
context_version
skill_provenance
integration_provenance
aggregation
evidence_inputs
rubric_summary
observation

# `events.jsonl` is an explicitly non-authoritative diagnostic journal. This
# supported inspection hook is exercised directly by integrity tests but is
# intentionally absent from canonical manifest/result recomputation.
_.read_events
alternative_explanations
success_definition
task_title
task_summary
agent_name
unlinked_traces
agent_traces
measurement_path
context_system_count
candidate_runtime
resolved_experiment_sha256
planned_prediction_count
publication_schema_version
bridge_endpoint
attestation_digest
delta_to_best
container_uri
ended_at
scenario_count
authored_asset_bytes
scenario_ids
evaluated_predictions
scenario_interactions
judge_sensitivity
row_count
row_digests
import_digest
maximum_traces
evidence_samples
suggested_tasks
next_questions
added_revision
added_at
unit
condition
comparator
population
exclusions
created_by
updated_by
context_digest
record_digest
llm_judge_used
mean
task_label
reason_code
latency_sec
research_label
study_label
fixed_conditions
varied_factors
treatment_arms
measured_outcomes
cell_limit
aligned_comparisons
behavioral_measures
outcome_summaries
score_summaries
release_note_coverage
model_config
selected_recipe
sanitization_report
planned_cells
queued_cells
running_cells
terminal_cells
elapsed_seconds
last_event_at
recommended_check_seconds
next_check_at
# Provider V1 fields are serialized into locked JSON artifacts.
display_name
provider_version
agent_config
behavior_assets
task_types
input_types
evaluator_types
lifecycle_types
stopping_policy
lifecycle
integration_config
implementation
evaluator_config
frozen_references
materialized_resources
lifecycle_outputs
runtime_artifacts
cleanup_obligations
credential_profile_names
runtime_lock_digest

# Harbor discovers these members dynamically on custom Agent classes.
SUPPORTS_ATIF
_.n_input_tokens
_.n_output_tokens

# Import-string registries and provider/materializer plugins.
EmptyContextProvider
AgentsMdContextProvider
LatMdContextProvider
Mem0ContextProvider
GraphitiContextProvider
AiderRepoMapContextProvider
GitNexusContextProvider
RagContextProvider
_Mem0FastEmbedder
SweQaProMaterializer
GeneratedCapabilityMaterializer
AuthoredTaskMaterializer
# Harbor imports this terminal-evidence plugin by the class path rendered into
# each job configuration; its lifecycle methods are invoked by Harbor.
DurableHarborTerminalPlugin
_.on_job_start
_.on_job_end

# Supported public analysis/builders.
factorial_difference_in_differences
build_trace_selection
# Imported by the checked-in zero-model MCP qualification entrypoints under
# examples/comparisons/wandb-mcp-maintenance/.
qualify_locked_mcp_revisions
verify_hosted_source_conformance
prepare_hosted_project

# HTTP handlers and framework callbacks registered by decorators/metaclasses.
context_search
guard
security_headers
research_error_handler
validation_error_handler
request_validation_error_handler
create_research
get_research
get_catalog
get_research_catalog
comparison_catalog
comparison_readiness
comparison_preview
comparison_request_approval
comparison_start
comparison_watch
comparison_result
get_study_context
get_research_context
update_research
preview_trace_audit
preview_research_trace_audit
start_trace_audit
start_research_trace_audit
get_trace_audit
derive_task_suite_preview
preview_controlled_study
request_controlled_study_approval
get_latest_controlled_study_approval_preview
experiment_events
watch_experiment_events
get_outcome
authenticate
healthz
readyz
compact_response
responses
chat_completions
ag_ui

# MCP tools/resources/prompts registered by FastMCP decorators.
fugue_catalog
fugue_comparison_catalog
fugue_comparison_readiness
fugue_comparison_preview
fugue_comparison_request_approval
fugue_comparison_start
fugue_comparison_watch
fugue_comparison_result
fugue_research_catalog
fugue_study_create
fugue_research_create
fugue_study_context
fugue_research_context
fugue_study_record
fugue_research_record
fugue_trace_audit_preview
fugue_trace_audit_start
fugue_task_suite_derive_preview
fugue_research_task_suite_derive_preview
fugue_experiment_preview
fugue_study_preview
fugue_experiment_start
fugue_study_start
fugue_study_request_approval
fugue_experiment_get
fugue_study_get
fugue_experiment_watch
fugue_study_watch
fugue_experiment_cancel
fugue_study_cancel
fugue_result_record
fugue_research_result_record
research_context
study_context
trace_audit
experiment_status
experiment_outcome
controlled_study_status
controlled_study_outcome
optimize_agent_use_case
design_controlled_experiment
interpret_experiment
advance_research_cycle

# Public loop-preparation API used by operator scripts outside the package tree.
build_comparison_failure_lock
write_comparison_failure_lock
read_comparison_failure_lock
# Public intervention-source helpers used by the checked-in loop operator
# scripts and by third-party operator automation outside the package tree.
write_intervention_component_lock
verify_intervention_component_checkout
# Supported standalone-library surfaces consumed by installed-package clients.
standalone_templates
changed_dimension
_.publication_receipt

# Intentionally unused symbols in shipped mutation/control fixtures. Their
# unused state is the behavior a template asks an Agent to diagnose or change.
Account
notifications_enabled
create_widget
DATABASE_PATH

# Protocol, stdlib server, FastAPI state, and Textual callback/member access.
_.input_messages
_.output_messages
_.create_batch
_._normalize_provider_models_schema
_.evaluation_urls
_.do_GET
_.do_POST
_.log_message
_.trace_audits
_.row_factory
_.access_subject
_.research_service
_.research_worker_embedded
_.watch
_.reconstruct_study
# Public recovery operations invoked by an external controller after
# authoritative cost or interrupted-execution evidence arrives.
_.select_canonical
_.reconcile_interrupted_physical
# Public adapter intentionally remains disconnected from comparison execution
# until the stacked evidence/trace layer can satisfy its fail-closed callbacks.
execute_recoverable_cells
DEFAULT_CSS
TITLE
ENABLE_COMMAND_PALETTE
CSS
BINDINGS
_.on_mount
_.on_unmount
_.on_button_pressed
_.on_select_changed
_.on_selection_list_selected_changed
_.on_input_changed
_.on_data_table_row_highlighted
_.on_data_table_row_selected
_.action_show_compose
_.action_show_results
_.action_next_step
_.action_previous_step
_.action_help
_.action_run
_.analysis_result
_.display
_.disabled

# Serialized runtime-manifest field and Harbor's dynamic ``--env`` import.
_.required_secrets
FugueWandbEnvironment
